### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Stanzilla** [JakePartusch/psi-action#2]
Hey there, I'm pretty much using the setup from your blog post

```yaml
- name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: "manticore-docs"
          max_timeout: 180

      - name: Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitFor200.outputs.url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1
        with:
          url: ${{ steps.waitFor200.outputs.url }}
```

but I'm getting 

```
Running Page Speed Insights 7s
##[error]Cannot read property 'type' of undefined
Run jakepartusch/psi-action@v1
Running Page Speed Insights for https://deploy-preview-199--manticore-docs.netlify.app
##[error]Cannot read property 'type' of undefined
```

on my runs. Any idea?
